apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent
    env:
      - name: "HOME"
        value: "/home/jenkins"
    volumeMounts:
    - mountPath: "/home/jenkins"
      name: "workspace-volume"
      readOnly: false
  volumes:
    - name: workspace-volume
      hostPath:
        path: /c/Users/MilindChavan/k8s/app-dependencies